#!/bin/sh

case "$1" in
  start)
    printf "Loading music driver: "
    insmod /lib/modules/6.6.78-v8/extra/music_input_driver.ko
    echo "OK"
    
    sleep 1
    
    printf "Starting music daemon: "
    start-stop-daemon -S -b -m -p /var/run/music_daemon.pid \
        -x /usr/bin/music_daemon
    echo "OK"
    ;;
  stop)
    printf "Stopping music daemon: "
    start-stop-daemon -K -p /var/run/music_daemon.pid
    echo "OK"
    
    printf "Unloading music driver: "
    rmmod music_input_driver
    echo "OK"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
